# Generated by Django 5.2.17 on 2026-09-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机台名称')),
                ('machine_type', models.CharField(choices=[('overflow', '溢流染色机'), ('jet', '喷射染色机'), ('jigger', '卷染机'), ('airflow', '气流染色机')], default='overflow', max_length=20, verbose_name='机型')),
                ('capacity_kg', models.PositiveIntegerField(default=500, verbose_name='容量(kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('customer', models.CharField(max_length=100, verbose_name='客户')),
                ('fabric_type', models.CharField(max_length=100, verbose_name='布种')),
                ('composition', models.CharField(blank=True, max_length=100, verbose_name='成分')),
                ('color', models.CharField(max_length=50, verbose_name='颜色')),
                ('color_no', models.CharField(blank=True, max_length=50, verbose_name='色号')),
                ('quantity_kg', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='订单数量(kg)')),
                ('delivery_date', models.DateField(verbose_name='交期')),
                ('priority', models.CharField(choices=[('normal', '普通'), ('urgent', '加急'), ('critical', '特急')], default='normal', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待生产'), ('producing', '生产中'), ('completed', '已完成'), ('shipped', '已出货')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DyeVat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_no', models.CharField(max_length=50, unique=True, verbose_name='缸号')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='本缸重量(kg)')),
                ('status', models.CharField(choices=[('unscheduled', '待排缸'), ('scheduled', '已排缸'), ('producing', '生产中'), ('inspecting', '待检验'), ('completed', '已完成')], default='unscheduled', max_length=20, verbose_name='状态')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='计划开始')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='计划结束')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='实际开始')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='实际结束')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vats', to='production.machine', verbose_name='机台')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vats', to='production.order', verbose_name='订单')),
            ],
            options={
                'ordering': ['vat_no'],
            },
        ),
        migrations.CreateModel(
            name='ProcessParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bath_ratio', models.CharField(default='1:10', max_length=20, verbose_name='浴比')),
                ('dye_temp', models.DecimalField(decimal_places=1, default=98.0, max_digits=5, verbose_name='染色温度(℃)')),
                ('dye_time', models.PositiveIntegerField(default=40, verbose_name='保温时间(min)')),
                ('ph_value', models.DecimalField(decimal_places=1, default=7.0, max_digits=3, verbose_name='pH值')),
                ('heating_rate', models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='升温速率(℃/min)')),
                ('dyes', models.JSONField(blank=True, default=list, help_text='[{"name":"分散红","pct":1.2}]', verbose_name='染料配方')),
                ('auxiliaries', models.JSONField(blank=True, default=list, help_text='[{"name":"匀染剂","gpl":1.0}]', verbose_name='助剂')),
                ('note', models.TextField(blank=True, verbose_name='工艺备注')),
                ('vat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='production.dyevat', verbose_name='缸号')),
            ],
        ),
        migrations.CreateModel(
            name='QualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(max_length=50, unique=True, verbose_name='异常单号')),
                ('issue_type', models.CharField(choices=[('color_diff', '色差'), ('color_flower', '色花'), ('stain', '沾污'), ('fastness', '色牢度不合格'), ('defect', '布面疵点'), ('strength', '强力不足'), ('other', '其他')], max_length=20, verbose_name='异常类型')),
                ('severity', models.CharField(choices=[('minor', '轻微'), ('major', '一般'), ('critical', '严重')], default='major', max_length=10, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('reporter', models.CharField(max_length=50, verbose_name='上报人')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='production.dyevat', verbose_name='缸号')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReworkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rework_type', models.CharField(choices=[('redye', '复染'), ('strip_redye', '剥色重染'), ('resetting', '回修定型'), ('rewash', '回洗'), ('other', '其他')], default='redye', max_length=20, verbose_name='返修方式')),
                ('plan', models.TextField(verbose_name='处理方案')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='负责人')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '进行中'), ('done', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('result', models.CharField(blank=True, choices=[('', '待定'), ('pass', '合格'), ('fail', '不合格')], default='', max_length=10, verbose_name='返修结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reworks', to='production.qualityissue', verbose_name='关联异常')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('pretreatment', '前处理'), ('dyeing', '染色'), ('soaping', '皂洗'), ('fixing', '固色'), ('dewatering', '脱水'), ('drying', '烘干'), ('setting', '定型'), ('inspection', '检验'), ('packing', '包装')], max_length=20, verbose_name='工序')),
                ('seq', models.PositiveSmallIntegerField(default=0, verbose_name='顺序')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('done', '已完成'), ('abnormal', '异常')], default='not_started', max_length=20, verbose_name='状态')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作工')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.dyevat', verbose_name='缸号')),
            ],
            options={
                'ordering': ['vat', 'seq'],
                'unique_together': {('vat', 'step')},
            },
        ),
    ]
