# Generated by Django 5.2.17 on 2026-09-13 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('fabric_type', models.CharField(max_length=100, verbose_name='适用布种')),
                ('color_no', models.CharField(blank=True, max_length=50, verbose_name='色号')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='颜色')),
                ('customer', models.CharField(blank=True, max_length=100, verbose_name='客户确认样')),
                ('bath_ratio', models.CharField(default='1:10', max_length=20, verbose_name='浴比')),
                ('dye_temp', models.DecimalField(decimal_places=1, default=98.0, max_digits=5, verbose_name='染色温度(℃)')),
                ('dye_time', models.PositiveIntegerField(default=40, verbose_name='保温时间(min)')),
                ('ph_value', models.DecimalField(decimal_places=1, default=7.0, max_digits=3, verbose_name='pH值')),
                ('heating_rate', models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='升温速率(℃/min)')),
                ('dyes', models.JSONField(blank=True, default=list, verbose_name='染料配方')),
                ('auxiliaries', models.JSONField(blank=True, default=list, verbose_name='助剂')),
                ('note', models.TextField(blank=True, verbose_name='工艺备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='processparameter',
            name='template',
            field=models.ForeignKey(blank=True, help_text='套用的模板（值为快照，模板后续改动不影响本缸）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_params', to='production.processtemplate', verbose_name='执行模板'),
        ),
    ]
